version: "3.7"

services:

  flask:
    build: ./flask
    container_name: flask
    restart: always
    environment:
      - APP_NAME=MyFlaskApp
    expose:
      - 8080
    volumes:
      - ./flask/app:/app/app
      # - ./flask/.env:/app/.env

  nginx:
    build: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"

  database:
    image: mariadb
    container_name: database
    restart: always
    environment:
      MARIADB_USER: 'user'
      MARIADB_PASSWORD: '7baif87byf'
      MARIADB_ROOT_PASSWORD: 'vuis78gfevyfiu9e7fyfb'
    expose:
      - 3306
    ports:
      - 3306:3306
    volumes:
    - ./mysql/data:/var/lib/mysql
    - ./mysql/init.sql:/docker-entrypoint-initdb.d/dump.sql